import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        {children}
        <Toaster 
          style={
            {
              "--normal-bg": "var(--color-cream)",
              "--normal-border": "var(--color-taupe)",
              "--normal-text": "var(--color-ebony)",
              "--success-bg": "var(--color-cream)",
              "--success-border": "var(--color-olive)",
              "--success-text": "var(--color-ebony)",
              "--error-bg": "var(--color-cream)",
              "--error-border": "#dc2626",
              "--error-text": "var(--color-ebony)",
            } as React.CSSProperties
          }
        />
      </body>
    </html>
  );
}
